### ISSUE TITLE
Create and update multiple entities

### ISSUE THREAD

**Issue by au999** [MicroFocus/alm-octane-js-rest-sdk#16]
Is it possible to create/update multiple entities with one request to Octane?

Passing { data: [ objects ]} results in an error.

**Comment by slbruce** [comment]
@maxpower999 I'll look into this

**Comment by slbruce** [comment]
@au999 I have created a pull request for this fix.  If you would like you can download the code and see if it fixes the issue of bulk update

**Comment by slbruce** [comment]
Fixed in 12.60.4
