### ISSUE TITLE
Not respecting no_proxy when setting proxy env vars

### ISSUE THREAD

**Issue by ChrisSG** [MicroFocus/alm-octane-js-rest-sdk#23]
Connections will fail to internal URLs if proxy is set and the URL is excluded by no_proxy in env vars. 

The request module already handles the env vars for proxy correctly already. No need to handle this here!

PR https://github.com/MicroFocus/alm-octane-js-rest-sdk/pull/22

**Comment by LauraBuzas** [comment]
Fixed in #33
