### ISSUE TITLE
sdk doesn't recognize user defined field (udf's)

### ISSUE THREAD

**Issue by panama69** [MicroFocus/alm-octane-js-rest-sdk#25]

**Comment by panama69** [comment]
The 
```
octane.defects.update({id: changeId, rework_counter_udf: 5}, ....
```

I am able to update all other system defined fields such as
```
octane.defects.update({id: changeId, story_points: 10}, ....
```
but not udf's.

**Comment by slbruce** [comment]
In order to recognise the UDFs you need to run the `generate_default_routes.js` script _after_ you have created the UDFs.  The sdk works by having all the fields generated within it (for good or for bad)
