### ISSUE TITLE
No property `create` of undefined when creating a defect

### ISSUE THREAD

**Issue by downzer0** [MicroFocus/alm-octane-js-rest-sdk#26]
Following the README for creating a defect, I get an error because `create` isn't a property on undefined. In this case, `defects` doesn't exist on `octane`.

My redacted file:

```javascript
const Octane = require("@microfocus/alm-octane-js-rest-sdk");

require("dotenv");

const octane = new Octane({
  protocol: "https",
  host: process.env.CLIENT_HOST,
  port: 443,
  shared_space_id: 123,
  workspace_id: 456
});

octane.authenticate({
  username: process.env.CLIENT_USERNAME,
  password: process.env.CLIENT_PASSWORD
}, (err) => {
  if (err) {
    console.log("Authentication error: ", err.message);
    return;
  }

  // create a defect
  const defect = {
    name: "defect",
    parent: 124,
    severity: "high"
  };

  octane.defects.create(defect, (err, defect) => {
    if (err) {
      console.log("Action error: ", err);
    }
  });
});
```

When I log `octane`, I get a bunch of properties, none of which are `defects`.

Is the README out of date, or am I missing something?

**Comment by downzer0** [comment]
@slbruce Good morning. Do you have an update on this, by any chance?

**Comment by slbruce** [comment]
> @slbruce Good morning. Do you have an update on this, by any chance?

@downzer0 I have not had a chance to look at this yet but I will be checking this week

**Comment by downzer0** [comment]
@slbruce I re-ran the routes config and it seems to have cleared it up. I guess something didn't go quite right the first time. Now to just diagnose the permissions issues. I will close this issue.

As for permissions, it is a bit unclear which permissions are needed in order to create defects with this SDK. I have a user with an API key, but all of the preset permission levels result in a 403. I know this is unrelated, but any ideas?
