### ISSUE TITLE
Add support for expanding reference fields

### ISSUE THREAD

**Issue by XtraSonic** [MicroFocus/alm-octane-js-rest-sdk#43]
Previously requests which included the "fields" query parameter were made with `.../api/shared_spaces/<space_id>/workspaces/<workspace_id>/defects?fields=author,release,phase,priority,team`. Octane used to return more information about reference fields, but this functionality was changed. Now it only returns enough information to identify the reference field without additional information. Octane also added a way to query extra fields for reference fields  using the following format `.../api/shared_spaces/<space_id>/workspaces/<workspace_id>/defects?fields=author{name},release,phase{name},priority,team` and we also need to support this feature in the sdk

**Comment by silviucanton99** [comment]
This can be done by directly specifying the extended fields in the fields method as comma-separated strings:
`await octane.get(Octane.entityTypes.defects).fields('name', 'owner', 'phase{name}').execute()`
