### ISSUE TITLE
Multiple issues/improvements needed/required/suggested

### ISSUE THREAD

**Issue by andrei-b-mf** [MicroFocus/alm-octane-js-rest-sdk#45]
Hi, I have updated to the latest version and I found that there are many things that do not work as I need or as I expected, so I will mention here a list of requests/problems:

1. does not allow you to make custom calls except entity calls. Like that, cannot access custom URLs(analytics\ci in my case), and additionally cannot set custom headers. I had to do something like this in the code to make it work, but this is wrong as I access internal code that skips some logic from the SDK: `await octaneSDKConnection._requestHandler._requestor.post(testResultObj)`
2. has at least one deprecated library request-promise-native (Did not check others. Its cool though that vulnerable libraries were removed)
3. does not filter out fields from entities that are not possible to modify on the objects. update crashes with 403 stating version_stamp is not modifiable, while old version with routes works and does not send this field. Solution: had to create new objects only with the fields I want to modify, which might be ok but still strange that this was allowed before and not now.
4. IntelliSense is not working in IntelliJ, simply because the library might either be wrongly configured or because it lacks typescript. It would be cool if you convert it to typescript version in future so we can use strict types and avoid going into the source code or online documentation to find out how to use the methods.
5. It lacks the explicit authenticate/signIn method, and every time at first usage we get 401, obviously. Maybe provide one, so that we don't get 401 all time at the beginning, if we call it by hand?

**Comment by andrei-b-mf** [comment]
If you want to use some library for HTTP requests, then it seems that [AXIOS](https://www.npmjs.com/package/axios) is a good one, which I know some people use in production. @LauraBuzas

**Comment by silviucanton99** [comment]
- Added method for executing custom requests
- Added authenticate method
- Converted project to typescript in order to facilitate autocompletion
- Changed request-promise-native library to Axios
